services:
  web:
    build:
      context: ./backend/app
      dockerfile: Dockerfile
    container_name: Just_ToDo_Django
    command: /app/entrypoint.sh
    volumes:
      - ./backend/app:/app
    working_dir: /app
    env_file:
      - ./backend/app/.env
    depends_on:
      - db
      - redis
    ports:
      - "8100:8000"
    networks:
      - todonet
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - todonet

  db:
    image: postgres:16
    container_name: postgres_db
    volumes:
      - ./backend/postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/app/.env
    networks:
      - todonet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: todo_frontend
    ports:
      - "80:80"
    networks:
      - todonet
    restart: unless-stopped

  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./backend/nginx/conf.d:/etc/nginx/conf.d
      - ./backend/app/static:/static
      - ./backend/app/media:/media
      - ./frontend/dist:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - web
      - frontend
    networks:
      - todonet
    restart: unless-stopped

networks:
  todonet:
    driver: bridge

